### ISSUE TITLE
Each link opens in a new window

### ISSUE THREAD

**Issue by Saniewski** [LemonTasteBlue/ElectronWebAppWrapper#1]
**Steps to reproduce:**
1. Click on a link.
2. *Link opens in a new window.*

**Expected result:**
*Link opens in a new tab in the default browser.*

**Impacted version:**
Any.

**Comment by pmroz1** [comment]
In #2 pr, added option to open url in user default browser, instead of opening new windows.
Enabled by:
`"openExternal": true` in `appconf.json`
